# Generated by Django 4.1.3 on 2023-05-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('years_ago', models.PositiveIntegerField()),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.epic')),
            ],
        ),
        migrations.CreateModel(
            name='EventHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventVillain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.event')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others/Unknown', 'Others/Unknown')], max_length=100)),
                ('description', models.TextField()),
                ('is_immortal', models.BooleanField(default=True)),
                ('benevolence_factor', models.PositiveSmallIntegerField(help_text='How benevolent this hero is?')),
                ('arbitrariness_factor', models.PositiveSmallIntegerField(help_text='How arbitrary this hero is?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.category')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djtest.hero')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djtest.hero')),
            ],
            options={
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others/Unknown', 'Others/Unknown')], max_length=100)),
                ('description', models.TextField()),
                ('is_immortal', models.BooleanField(default=False)),
                ('malevolence_factor', models.PositiveSmallIntegerField(help_text='How malevolent this villain is?')),
                ('power_factor', models.PositiveSmallIntegerField(help_text='How powerful this villain is?')),
                ('is_unique', models.BooleanField(default=True)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.category')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.origin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
        migrations.AddField(
            model_name='hero',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.origin'),
        ),
        migrations.AddField(
            model_name='hero',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djtest.hero'),
        ),
        migrations.AddField(
            model_name='eventvillain',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.villain'),
        ),
        migrations.AddField(
            model_name='eventhero',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtest.hero'),
        ),
        migrations.AddField(
            model_name='epic',
            name='participating_heroes',
            field=models.ManyToManyField(to='djtest.hero'),
        ),
        migrations.AddField(
            model_name='epic',
            name='participating_villains',
            field=models.ManyToManyField(to='djtest.villain'),
        ),
    ]
